### ISSUE TITLE
ModuleNotFoundError: No module named 'AudioLogger' / ImportError: cannot import name 'CopyLogger' from partially initialized module 'SpyWare'

### ISSUE THREAD

**Issue by windowshopr** [mauricelambert/SpyWare#1]
Windows 10
Python 3.10
`pip install pyautogui opencv-python pillow pyperclip pynput pyaudio`
`pip install SpyWare`
`SpyWare`

```
PS C:\Users\...\Desktop\Spy> SpyWare
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\site-packages\SpyWare\__init__.py", line 58, in <module>
    import AudioLogger
ModuleNotFoundError: No module named 'AudioLogger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\Scripts\SpyWare-script.py", line 33, in <module>
    sys.exit(load_entry_point('SpyWare==1.0.2', 'console_scripts', 'SpyWare')())
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\Scripts\SpyWare-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\site-packages\SpyWare\__init__.py", line 68, in <module>
    from . import CopyLogger
ImportError: cannot import name 'CopyLogger' from partially initialized module 'SpyWare' (most likely due to a circular import) (C:\Users\...\AppData\Local\Programs\Python\Python310\lib\site-packages\SpyWare\__init__.py)
```

**Comment by mauricelambert** [comment]
Thanks for the issue ! I debug that, it's just an error in the directory/filename.

**Comment by mauricelambert** [comment]
I commit and send on pypi a new version that fix the bug.

You can try it with:

```bash
pip install --upgrade SpyWare
SpyWare
```

**Comment by windowshopr** [comment]
Now here's a new one for ya!

```
PS C:\Users\...\OneDrive\Desktop\Hacking> SpyWare
Traceback (most recent call last):
  File "c:\users\...\appdata\local\programs\python\python3\lib\site-packages\SpyWare\__init__.py", line 58, in <module>
    import AudioLogger
ModuleNotFoundError: No module named 'AudioLogger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\...\appdata\local\programs\python\python3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\...\appdata\local\programs\python\python3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\AppData\Local\Programs\Python\Python3\Scripts\SpyWare.exe\__main__.py", line 4, in <module>
  File "c:\users\...\appdata\local\programs\python\python3\lib\site-packages\SpyWare\__init__.py", line 69, in <module>
    from . import DomainsLogger
  File "c:\users\...\appdata\local\programs\python\python3\lib\site-packages\SpyWare\DomainsLogger\__init__.py", line 58, in <module>
    from .DomainsLogger import (
  File "c:\users\...\appdata\local\programs\python\python3\lib\site-packages\SpyWare\DomainsLogger\DomainsLogger.py", line 315, in <module>
    class CacheAppData:
  File "c:\users\...\appdata\local\programs\python\python3\lib\site-packages\SpyWare\DomainsLogger\DomainsLogger.py", line 328, in CacheAppData
    def domains_generator(self, directory: str) -> Iterator[List[bytes]]:
TypeError: 'ABCMeta' object is not subscriptable
```

**Comment by mauricelambert** [comment]
Are you sure you are in Python 3.10 ?

```
~# python3.10 -c "from collections.abc import Iterator; print(Iterator[str])"
collections.abc.Iterator[str]
~# python3.8 -c "from collections.abc import Iterator; print(Iterator[str])"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'ABCMeta' object is not subscriptable
~#
```

This code should work in python 3.10.

I will fix it using `typing.Iterable`:

```bash
~# python3.8 -c "from typing import Iterable; print(Iterable[str])"
typing.Iterable[str]
~#
```

**Comment by mauricelambert** [comment]
I commit and send on pypi a new version that fix the bug.

You can try it with:

```bash
pip install --upgrade SpyWare
SpyWare
```
