### ISSUE TITLE
No module named 'AudioLogger'

### ISSUE THREAD

**Issue by CamoCatX** [mauricelambert/SpyWare#3]
I copied and pasted this script:

`from` `SpyWare` `import` `spyware`
`spyware()`
---------------------------------------------------------------------------------------------------------------------------------------------
This, according to the readme, should of started SpyWare. But it did not. Instead, I received this error:
---------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "c:/Users/cdsdc/Desktop/Coding/PWN/SpyWare", line 1, in <module>
    from SpyWare import spyware
  File "C:\Users\cdsdc\AppData\Roaming\Python\Python38\site-packages\SpyWare\__init__.py", line 67, in <module>
    from . import AudioLogger
  File "C:\Users\cdsdc\AppData\Roaming\Python\Python38\site-packages\SpyWare\AudioLogger\__init__.py", line 64, in <module>
    from AudioLogger import (
ModuleNotFoundError: No module named 'AudioLogger'
---------------------------------------------------------------------------------------------------------------------------------------------

When I did what I usually do when receiving this error, (python -m pip install AudioLogger) it simply said:

---------------------------------------------------------------------------------------------------------------------------------------------
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement AudioLogger (from versions: none)
ERROR: No matching distribution found for AudioLogger
---------------------------------------------------------------------------------------------------------------------------------------------

This means that I do not have the matching python version. (I was using 3.8).

How would I go about fixing this?

**Comment by CamoCatX** [comment]
I figured this out on my own.
