### ISSUE TITLE
charmp issue

### ISSUE THREAD

**Issue by TeteuXD2** [mauricelambert/SpyWare#8]
i made it run on my old pc for testing and this showed up

Exception in thread Thread-5 (run_for_ever):
Traceback (most recent call last):
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Lib\site-packages\SpyWare\FilesLogger\FilesLogger.py", line 141, in run_for_ever
    fileslogger.get_filenames(normcase("/"))
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Lib\site-packages\SpyWare\FilesLogger\FilesLogger.py", line 191, in get_filenames
    get_filenames(join(directory, file.name))
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Lib\site-packages\SpyWare\FilesLogger\FilesLogger.py", line 191, in get_filenames
    get_filenames(join(directory, file.name))
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Lib\site-packages\SpyWare\FilesLogger\FilesLogger.py", line 203, in get_filenames
    self.persistent_save()
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Lib\site-packages\SpyWare\FilesLogger\FilesLogger.py", line 267, in persistent_save
    file.write(self.data)
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 11-14: character maps to <undefined>

**Comment by mauricelambert** [comment]
Thanks for opening this issue, i think i should define the encoding or write in *bytes mode* (`ab`) in the file. I will fix it.

**Comment by mauricelambert** [comment]
I have fixed this issue, by encoding with python default encoding (`utf-8`, instead of filesystem default encoding, in your case: `cp1252`).
