### ISSUE TITLE
another traceback

### ISSUE THREAD

**Issue by TeteuXD2** [mauricelambert/SpyWare#9]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Scripts\SpyWare.exe\__main__.py", line 7, in <module>
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Lib\site-packages\SpyWare\SpyWare.py", line 576, in main
    install()
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Lib\site-packages\SpyWare\SpyWare.py", line 410, in install
    rename(executable, path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Nice\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\SpyWare' -> 'C:\\Users\\Nice\\AppData\\Roaming\\SoliderSound\\web-ext'

**Comment by TeteuXD2** [comment]
when i run on admin cmd, it gives the same error but on a different file
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Scripts\SpyWare.exe\__main__.py", line 7, in <module>
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Lib\site-packages\SpyWare\SpyWare.py", line 576, in main
    install()
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python311\Lib\site-packages\SpyWare\SpyWare.py", line 410, in install
    rename(executable, path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Nice\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\SpyWare' -> 'C:\\Users\\Nice\\AppData\\Roaming\\JPEXS\\cache'

**Comment by mauricelambert** [comment]
I think this is not a bug... You have installed the project as a python project and you launch it with `--install` but the `--install` is used to *hide* the spyware on the file system, so it's used on *target system* not on a developer system with a python installation. You should *install* (start with the `--install` option) only with the binaries. Use it as developer or tester in a python package (to access to the code) but install only the *python package executable*.

**Comment by mauricelambert** [comment]
Can you explain me how you have start the *SpyWare* and confirm me you have used `pip` to install the project ?

**Comment by TeteuXD2** [comment]
just using "python spyware --install"

**Comment by mauricelambert** [comment]
Okay so your `spyware` file is not an executable.

To start your command you should have a python installed, this project may be used on a *victim* computer, without any python interpreter installed, this is the reason why i add a compiled version in the releases. You should use the `--install` option only with executable because it's used to hide the `spyware` executable, you probably don't want to hide the spyware on your own system.
